### ISSUE TITLE
Support for Django 1.10?

### ISSUE THREAD

**Issue by bmcguirk** [texperience/django-bootstrap-ui#1]
Hi there - very cool app you've got here, and I think it'd be great to use. Unfortunately, for compliance reasons, I really need to use Django 1.10. Do you have any thoughts on supporting it?

**Comment by timorieber** [comment]
Thank you for your question. Support for Django 1.10 is definitely a feature I would have implemented sooner or later anyway, so I'll see when I can get time in the next few weeks.
