### ISSUE TITLE
what is the way to use html tags in django_bootstrap_ui

### ISSUE THREAD

**Issue by shashankaryan** [texperience/django-bootstrap-ui#7]
I was working with django_bootstrap_ui , in {% load bootstrap_ui_tags %}, there are very few tags loaded. i am unable to load navbar, carousel, etc. Can anyone please tell me how can i add it?

**Comment by timorieber** [comment]
These components are not implemented yet, please refer to http://django-bootstrap-ui.readthedocs.io/en/stable/template_tag_api/components/index.html for a complete list of tags available.
